---
    name: Execução Manual
    on:
      workflow_dispatch: null
    jobs:
      e2e-tests:
        runs-on:
          - ubuntu-latest
        steps:
          - uses: actions/checkout@v4
    
        #   - name: Instalando Yarn
        #     run: npm install -g yarn
    
        #   - name: Instalando dependências
        #     run: yarn
    
          - name: Instalando Cypress
            run: npm install cypress@13.5.1 --dev
            
          - name: Instalando Mochawesome
            run: npm i --save-dev cypress-mochawesome-reporter
    
          - name: Testes E2E (end-to-end)
            run: npx cypress run
    
          - uses: actions/upload-artifact@v4
            if: ${{ !cancelled() }}
            with:
              name: relatorio-de-testes
              path: ./cypress/reports
    